### ISSUE TITLE
Add safe-events-service to infrastructure

### ISSUE THREAD

**Issue by moisses89** [safe-global/safe-infrastructure#100]
# Description
This issue is created to add to safe-infrastructure the new safe-events https://github.com/safe-global/safe-events-service.

# Tasks
 - [x] Include safe events service in docker compose
 - [x] Update README
 - [x] #113

**Comment by moisses89** [comment]
Marked as blocked until add the new client-gateway https://github.com/safe-global/safe-infrastructure/issues/99

**Comment by Uxio0** [comment]
This should be unlocked now

**Comment by moisses89** [comment]
I just created an issue https://github.com/safe-global/safe-events-service/issues/92 this should be done first
