### ISSUE TITLE
Programmatic configuration of safe master copy

### ISSUE THREAD

**Issue by peterpolman** [safe-global/safe-infrastructure#102]
Hi team!👋  I'm using safe-infrastructure in a github workflow together with a hardhat node and I have trouble with the required manual configuration steps. Locally I'm using the txs admin UI to set the safe master copy address. Is there a (convenient) way to configure the safe master copy address programmatically?

**Comment by peterpolman** [comment]
Ended up sharing a migration through docker volumes which sets default values. As this is a bit hacky I will change that into a manage.py custom command which should allow to create a safe master copy through the CLI. Want me to add a PR for that?

All in all it worked out fine, the infra is now running in our GH actions and the API tests run against it nicely ❤️ 🙏

**Comment by Uxio0** [comment]
> Ended up sharing a migration through docker volumes which sets default values. As this is a bit hacky I will change that into a manage.py custom command which should allow to insert a safe master copy through the CLI. Want me to add a PR for that?

Sure thing

> All in all it worked out fine, the infra is now running in our GH actions and the API tests run against it nicely ❤️ 🙏

Good to hear that!

**Comment by Uxio0** [comment]
Closing this due inactivity

**Comment by peterpolman** [comment]
@Uxio0 Better late than never I guess!😉 Submitted a PR but wasn't able to run test locally (see comment). The command works fine in our CI.
