### ISSUE TITLE
could not get messages

### ISSUE THREAD

**Issue by simonzg** [safe-global/safe-infrastructure#112]
Hi, I successfully bring up the infrastructure by docker-compose, and ran a safe-wallet-web with NEXT_PUBLIC_GATEWAY_URL_STAGING and NEXT_PUBLIC_GATEWAY_URL_PRODUCTION both configured to my client gateway. Everything seems to be working correctly, except for this error message:

![Screenshot 2023-08-10 at 10 55 45 AM](https://github.com/safe-global/safe-infrastructure/assets/7259860/ec823ac5-fce1-4991-a63c-a3a5a2bf8e5a)

which complains about this url is not accessible:

https://safe-gateway.meter.io/cgw/v1/chains/82/safes/0x7A83a59f9b810A65D62aD8454b898FA290e12882/messages

I checked the code of client gateway and it should provide this endpoint referring to tx service, and I checked the corresponding tx service api, it's working: 
https://safe-gateway.meter.io/txs/api/v1/safes/0x7A83a59f9b810A65D62aD8454b898FA290e12882/messages/

So I'm wondering maybe the latest docker image of client gateway does not include the latest code in repo? Is there any way to update it so that it provides all the information that safe-wallet-web wants? Thanks!

**Comment by SkySonR** [comment]
I faced the same issue. @simonzg did you solve it?

**Comment by Uxio0** [comment]
Is this issue still ongoing with the latest versions? (today we fixed some issues with last cgw version)
