### ISSUE TITLE
cgw service /v1/chains/:chainId/safes/:safeAddress 503 error

### ISSUE THREAD

**Issue by zctocm** [safe-global/safe-infrastructure#114]
## Bug description
I am experiencing errors when deploying a safe-wallet-web to support the BSC Testnet locally.
I have already submitted the transaction to BSC Testnet, the API route: v1/chains/97/safes/address is not working, but the main page of cgw API works.
I used Docker to get all the services up and running locally, as did the CGW related services.
## Environment
 - Browser: Chrome
 - Wallet: MetaMask
 - Chain: BSC Testnet

## Steps to reproduce
 1. Go to the main page.
 2. Create a safe account.

## Expected result
The cgw API works.

## Screenshots
![CleanShot 2023-09-17 at 16 11 01@2x](https://github.com/safe-global/safe-wallet-web/assets/16474758/2db78b08-c2ba-4af9-8821-21b5c8a1e6e5)
<img width="1634" alt="CleanShot 2023-09-17 at 16 12 15@2x" src="https://github.com/safe-global/safe-wallet-web/assets/16474758/16f1446a-94d0-487f-b667-520f4fed1c7f">
<img width="852" alt="CleanShot 2023-09-17 at 16 17 27@2x" src="https://github.com/safe-global/safe-wallet-web/assets/16474758/c4a146bf-b451-4412-af9c-ee71a6c51a8a">

**Comment by moisses89** [comment]
@zctocm take a look to this documentation, https://github.com/safe-global/safe-infrastructure/blob/main/docs/running_locally.md#step-3-add-your-chaininfo In your chain configuration I see that you are using localhost:8000 instead nginx:8000.
