### ISSUE TITLE
Error while running safe locally

### ISSUE THREAD

**Issue by AtharvDesignString** [safe-global/safe-infrastructure#120]
I am not able to start the ui. I checked the logs for the container & it exits with **error Command failed with signal "SIGKILL".**
<img width="685" alt="Screenshot 2023-10-26 at 4 55 02 PM" src="https://github.com/safe-global/safe-infrastructure/assets/137756013/649879ea-a7fa-4abf-a25c-7b261ee2f824">

**Comment by AtharvDesignString** [comment]
I don't know how but when I restarted the container it is working fine(I restarted yesterday also but didn't work today it is working)

**Comment by AtharvDesignString** [comment]
Now facing other issue. Not able to fetch the chains.
<img width="1429" alt="Screenshot 2023-10-27 at 11 49 08 AM" src="https://github.com/safe-global/safe-infrastructure/assets/137756013/1692acea-b4ec-4a22-b4a7-a37f883b52c0">

**Comment by Uxio0** [comment]
Closed by  #121
