### ISSUE TITLE
Issue to deploy safe infrastructure on a new chain

### ISSUE THREAD

**Issue by gnarco** [safe-global/safe-infrastructure#124]
We want to follow the procedure described it here : https://github.com/safe-global/safe-infrastructure

So we started adding our token to safe-deployment repo and request a bump in the NPM package. Done.

But, other libraries / tools still refer to old versions that does not include the newest safe-deployment package.

So, it seems that the whole stack needs to be bumped

is it right ? or do we miss something ? 

Thanks !

**Comment by mmv08** [comment]
Npm allows you to rewrite package resolutions. You can also patch the dependency to include your addresses. There are many solutions. If you wish to request a deployment/upgrade, please create an issue/PR in the corresponding repo.

**Comment by JABirchall** [comment]
How do I override the deployments package for the UI?

I had an issue open to increase the deployments version on the web repo and they wont because it needs to be tested. 
Its currently 5 months behind and my chain was added 3 months ago.

**Comment by mmv08** [comment]
> How do I override the deployments package for the UI?
> 
> The only thing stopping me from deploying safe-wallets for my chain is UI erroring `Uncaught (in promise) Error: Invalid CompatibilityFallbackHandler contract address`
> 
> I had an issue open to increase the deployments version on the web repo and they wont because it needs to be tested. Its currently 5 months behind and my chain was added 3 months ago.

Hmm, I'm not sure if it's possible with docker compose. Perhaps you could run the UI separately and update the dependency in the package.json there. CC @katspaugh

**Comment by katspaugh** [comment]
In the frontend repo, the following has to be done to support a new chain:

- The [[safe-deployments](https://github.com/safe-global/safe-deployments)](https://github.com/safe-global/safe-deployments) repo must be updated with the new chain and contract addresses, and a new version thereof must be released.
- The [[safe-core-sdk](https://github.com/safe-global/safe-core-sdk/tree/v3.3.3)](https://github.com/safe-global/safe-core-sdk/tree/v3.3.3) should be updated to use the new **safe-deployments** version and a new version of the SDK must be released.
- In the [[frontend repo](http://github.com/safe-global/safe-wallet-web)](http://github.com/safe-global/safe-wallet-web), both **safe-deployments** and **safe-core-sdk** versions must be set to those new versions.
- The new chain must be added and enabled in the [[safe-config-service](https://github.com/safe-global/safe-config-service)](https://github.com/safe-global/safe-config-service) via the Django admin.

**Comment by JABirchall** [comment]
> In the frontend repo, the following has to be done to support a new chain:
> 
>     * The [safe-deployments](https://github.com/safe-global/safe-deployments) repo must be updated with the new chain and contract addresses, and a new version thereof must be released.
> 
>     * The [safe-core-sdk](https://github.com/safe-global/safe-core-sdk/tree/v3.3.3) should be updated to use the new **safe-deployments** version and a new version of the SDK must be released.
> 
>     * In the [frontend repo](https://github.com/safe-global/safe-wallet-web), both **safe-deployments** and **safe-core-sdk** versions must be set to those new versions.
> 
>     * The new chain must be added and enabled in the [safe-config-service](https://github.com/safe-global/safe-config-service) via the Django admin.

the only step in that, is the webui isnt updated and is 5 versions behind the latest and 4 versions behind the SDK.

**Comment by katspaugh** [comment]
Great, then please feel free to update the packages in the UI, I'll accept the PR. 👍

**Comment by JABirchall** [comment]
> Great, then please feel free to update the packages in the UI, I'll accept the PR. 👍

Ok now that thats all merged and a release made, i updated the docker version and its now saying the contract address is invalid?
`Uncaught (in promise) Error: Invalid SafeProxyFactory contract address`

But it is there: https://explorer.hypra.network/address/0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2

Im not sure whats wrong here.

**Comment by happyleow** [comment]
@katspaugh Could you please upgrade both `Safe-Core-SDK` and `Safe-Wallet-Web` versions based on the new safe-deployment release version(v1.33.0)? any approximate timeframe for this? thanks.

**Comment by moisses89** [comment]
The ui version was updated in the .`env` file, is this still happening?.

**Comment by moisses89** [comment]
Last version should fix the issue, closing due inactivity.

**Comment by katspaugh** [comment]
Sorry I should've mentioned here: the packages were updated. So all good.
