### ISSUE TITLE
Issues with Safe Indexation on Arianee Supernet (Following Issue #124)

### ISSUE THREAD

**Issue by 0xWhiteleaf** [safe-global/safe-infrastructure#131]
This issue is a continuation of the discussion from [Issue #124](https://github.com/safe-global/safe-infrastructure/issues/124).

I am encountering an issue with the indexation process of Safe on the Arianee Supernet. Despite following the deployment and setup procedures, the creation of a Safe gets stuck at the "Indexation" stage. Below is a detailed account of the steps I've taken and the observations made.

# Steps to Reproduce
- Deployed "Safe Frontend" by cloning the repository and forcing the resolution of @safe-global dependencies to the correct versions containing Safe deployment information on Arianee Supernet _(@safe-global/**/@safe-global/safe-deployments: 1.28.0)_. 
- **The Safe Frontend launches correctly.**

- Configured and launched "Safe Infrastructure" with Docker Compose, stopping the "Safe Frontend" container as its already running in standalone mode.
- Configured Arianee Supernet in the Django administration interface.
- **The Arianee Supernet is detected by all "Safe Infrastructure" services with no anomalies in logs.**
- **Arianee Supernet appears correctly on the Safe Frontend. Safe creation is possible, but indexing does not complete.**

- I've checked that contracts are present at the deployment locations on Arianee Supernet.
- I've verified that the contracts deployed on Arianee Supernet match those deployed by Gnosis Safe on Ethereum.

- I've investigated the RPC method types supported by Supernet. _traces__ methods are not supported, while _eth__ methods, including _eth_getLogs_, are supported. So concluded that we definitely need to configure the Arianee Supernet in L2 mode.
- Deployed the Safe Infrastructure in L2 mode to enable the indexer to make RPC calls using _eth_getLogs_.
- Reinstalled Safe Infrastructure ensuring L2 mode was active, and selected L2 when adding the chain via the Django admin interface.

- Attempted to create a new Safe, but the process remained stuck on "Indexation".
- Also configured webhooks for cache clearing and also tried disabling the cache entirely to rule out cache-related issues.

So the creation of a Safe remains stuck on the "Indexation" step, with the indexer seemingly not detecting events, despite transactions for creating a Proxy for a Safe executing correctly on-chain. Any insights or suggestions for resolving this issue would be greatly appreciated. If there are further details or logs that could assist in troubleshooting, please let me know.

Furthermore, Arianee is willing to pay for support if necessary to resolve this issue. We are committed to finding a solution and are open to any available support options. Thanks a lot!

**Comment by leopaul36** [comment]
Hey @0xWhiteleaf, for what it's worth I found myself in a similar situation as you described.

Eventually what I missed was setting up [Proxy factories](http://localhost:8000/txs/admin/history/proxyfactory/) and [Safe master copies](http://localhost:8000/txs/admin/history/safemastercopy/) for my custom chain. After adding these, the indexing started working properly.

Hope this helps :+1:

**Comment by 0xWhiteleaf** [comment]
Hey @leopaul36
It did the job! Thanks a lot for this 👍 

I'm adding something else also, if you use a custom Layer 2 with a custom token as gas token, you'll also need to patch the `configuration.js` file inside the `cgw-web`.
It's located here inside the container: `dist/config/entities/configuration.js`
You'll need to add a key to the `balances.providers.safe.prices.chains` property, like what we did for Arianee:
```bash
...
prices: {
            baseUri: process.env.PRICES_PROVIDER_API_BASE_URI ||
                'https://api.coingecko.com/api/v3',
            apiKey: process.env.PRICES_PROVIDER_API_KEY,
            ...
            chains: {
                1: { nativeCoin: 'ethereum', chainName: 'ethereum' },
                10: { nativeCoin: 'ethereum', chainName: 'optimistic-ethereum' },
                100: { nativeCoin: 'xdai', chainName: 'xdai' },
                1101: { nativeCoin: 'ethereum', chainName: 'polygon-zkevm' },
                11155111: { nativeCoin: 'ethereum', chainName: 'ethereum' },
                1313161554: { nativeCoin: 'ethereum', chainName: 'aurora' },
                137: { nativeCoin: 'matic-network', chainName: 'polygon-pos' },
                324: { nativeCoin: 'ethereum', chainName: 'zksync' },
                42161: { nativeCoin: 'ethereum', chainName: 'arbitrum-one' },
                42220: { nativeCoin: 'celo', chainName: 'celo' },
                43114: { nativeCoin: 'avalanche-2', chainName: 'avalanche' },
                5: { nativeCoin: 'ethereum', chainName: 'ethereum' },
                56: { nativeCoin: 'binancecoin', chainName: 'binance-smart-chain' },
                8453: { nativeCoin: 'ethereum', chainName: 'base' },
                84531: { nativeCoin: 'ethereum', chainName: 'base' },
                11891: { nativeCoin: 'arianee', chainName: 'arianee' }, <-- This is the key
            },
        },
...
```

Hope this helps next adventurers

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rajnikyadav** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by louseee** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
