### ISSUE TITLE
404 Error on /cgw/v1/chains Endpoint - would Correct Endpoint be /cfg/api/v1/chains/ ?

### ISSUE THREAD

**Issue by metaver5o** [safe-global/safe-infrastructure#142]
Good day! 
I'm encountering the following error when trying to load the Safe:
```
GET http://xxx.compute-1.amazonaws.com:8000/cgw/v1/chains 404 (Not Found)
Error loading chains (Not Found)
```

The endpoint `:8000/cgw/v1/chains `does not seem to open:

![image](https://github.com/safe-global/safe-infrastructure/assets/8118992/6537d7dc-3b0d-4d0d-a0f9-2e6ae33c5e21)

However, the information can be found at the following endpoint: `:8000/cfg/api/v1/chains/`

![image](https://github.com/safe-global/safe-infrastructure/assets/8118992/662201b1-3e2a-4060-afaa-e7314ab3ac8b)

Could you please guide me on where to change/fix this configuration? 
I am running all Docker images from the latest version.
Thank you.

**Comment by metaver5o** [comment]
After considering the issue, I realized the redirection problems might be coming from the reverse-proxy. 
So, I updated my nginx.conf with the current one live in the repository, and it worked fine.
Thanks, everyone!

- Letting this here to encourage people who face similar redirection issue 😭

**Comment by SkyYap** [comment]
Hi I face the same issue but I can't identify which part of nginx conf. I need to change. Can you show me your code?
