### ISSUE TITLE
Invalid MultiSend contract address

### ISSUE THREAD

**Issue by lance-web3** [safe-global/safe-infrastructure#148]
I can access this page by adding some of the safe contract I know into watchlist but having error as per this screen capture

![Screenshot 2024-07-08 at 15 55 34](https://github.com/safe-global/safe-infrastructure/assets/37203010/f2310118-b6eb-482e-8635-ae0fd0ab8fe2)

**Comment by lance-web3** [comment]
![image](https://github.com/safe-global/safe-infrastructure/assets/37203010/bd74905f-5431-4c80-a942-125d59808576)

**Comment by Pana** [comment]
You need add your chain info in https://github.com/safe-global/safe-deployments/ and then update the safe-deployment version in the safe-wallet-web

**Comment by lance-web3** [comment]
@Pana 

> You need add your chain info in https://github.com/safe-global/safe-deployments/ 

It's already added:
https://github.com/safe-global/safe-deployments/pull/652
https://github.com/safe-global/safe-deployments/pull/663

> then update the safe-deployment version in the safe-wallet-web

What do you mean? In ui.env:
`NEXT_PUBLIC_SAFE_VERSION=1.4.1`

**Comment by lance-web3** [comment]
Is it because the safe-wallet-web haven't update their package.json?
```
"@safe-global/safe-deployments": "^1.36.0",
```
It is using the older version of safe-deployments

**Comment by lance-web3** [comment]
> If the official safe-wallet-web code still use the old version `safe-deployments`, you need fork the safe-wallet-web code, and use your own version safe-deployments, then build and deploy

@Pana btw, I tried to rebuild the safe-wallet-web with below, unfortunately the issue persists.
```
"@safe-global/safe-deployments": "^1.37.1",
```

**Comment by lance-web3** [comment]
fixed after update components to later version
