### ISSUE TITLE
`chain_logo.png` and `currency_logo.png` not accessible

### ISSUE THREAD

**Issue by simonzg** [safe-global/safe-infrastructure#149]
I'm trying to add a network with a customized network and currency logo, and the upload is successful. However, when I try to access the URL generated by cfg service
![Screenshot 2024-07-09 at 10 55 47 AM](https://github.com/safe-global/safe-infrastructure/assets/7259860/8fc6316d-10c0-4e0f-94e2-f177ad691382)

http://safegw.meter.io:8000/cfg/media/chains/82/chain_logo.png

it's giving me `Page not found`

![Screenshot 2024-07-09 at 10 58 55 AM](https://github.com/safe-global/safe-infrastructure/assets/7259860/4220b815-ae10-45da-9718-1eba7304a4a6)

Same thing for `currency_logo.png`.

**Comment by Pana** [comment]
same issue here

**Comment by simonzg** [comment]
I found a solution myself

1. set these two lines in `container_env_files/cfg.env`. 

```
MEDIA_URL=/media/
MEDIA_ROOT=/app/media
```

2. And then you need to add one line in `docker/nginx/nginx.conf` before `location /cfg/ {`

```
        rewrite ^(/(media)(/.*)?)$ /cfg$1 last;

```

3. Now docker compose up and re-upload images and you should be able to see logos.

![Screenshot 2024-07-11 at 5 18 10 PM](https://github.com/user-attachments/assets/3c6d45cc-1ead-479b-8312-ec2f9e353f84)

**Comment by lance-web3** [comment]
@simonzg the solution seems to only work for dns, can it work for IP?

on console, it is request to nginx instead of IP
![image](https://github.com/user-attachments/assets/56d0266b-60f9-4d39-8788-25b7594a445b)
