### ISSUE TITLE
503 Service unavailable for cgw/v1/chains call

### ISSUE THREAD

**Issue by akshar** [safe-global/safe-infrastructure#157]
Hi Team,

We're trying to setup safe via [docker-compose steps mentioned in this repo.](https://github.com/safe-global/safe-infrastructure/blob/main/docs/running_locally.md)  for custom chain. FE is up  at [https://safel2.sx.technology/](https://safel2.sx.technology/). Calls to [https://safel2.sx.technology/cgw/v1/chains](https://safel2.sx.technology/cgw/v1/chains) fails with `503 Service unavailable`.

## Additional information:
- Latest versions of all the services deployed.
- Config service (CFG) is running and returns correct chainConfig at [https://safel2.sx.technology/cfg/api/v1/chains/](https://safel2.sx.technology/cfg/api/v1/chains/)
- Client Gateway (CGW) seems to be running fine and returns correct version at [https://safel2.sx.technology/cgw/about](https://safel2.sx.technology/cgw/about)
- curl to CGW inside instance also returns 503. (Here 8000 is nginx port. No changes are made to nginx)
```
curl http://localhost:8000/cgw/v1/chains -L
{"code":503,"message":"Service unavailable"}
```
- CFG debug logs when FE main page is rendered: (suspect 301 redirect might be an issue https://github.com/safe-global/safe-config-service/blob/main/nginx/templates/nginx.conf.template#L52 🤔) 
```
 - - [18/Aug/2024:02:00:06 +0000] "GET /api/v1/chains?limit=20&offset=0 HTTP/1.0" 301 0 "-" "node"
2024-08-18 02:00:06,297 MT::GET::api/v1/chains/::35::200::/cfg/api/v1/chains/
 - - [18/Aug/2024:02:00:06 +0000] "GET /api/v1/chains/?limit=20&offset=0 HTTP/1.0" 200 1894 "-" "node"
 ```
 - CGW debug logs when FE main page is rendered:
 ```
{"build_number":"234a559","level":"error","message":{"chain_id":null,"client_ip":"xxx.xx.xx.xx","detail":"Service unavailable","method":"GET","origin":null,"path":"/v1/chains","response_time_ms":61.282322000712156,"route":"/v1/chains","safe_app_user_agent":null,"status_code":503},"request_id":"43837fda-36b7-410c-bc27-68edd468cd12","timestamp":"2024-08-18T02:00:06.304Z","version":"v1.53.0"}
```
-  `DJANGO_ALLOWED_HOSTS` & `CSRF_TRUSTED_ORIGINS` are set correctly (`localhost:*` , `nginix:*`, currendDomain allowed) in `cfg.env`. Same for `txs.env`

**Comment by dankostiuk** [comment]
Hi team, 

Any pointers? We are experiencing the same issue..
