### ISSUE TITLE
Is any documentation available?

### ISSUE THREAD

**Issue by stebansaa** [safe-global/safe-infrastructure#31]
Is there any documentation available? If not I will be happy to contribute the edition of one.

**Comment by fmrsabino** [comment]
Besides the Readme file we have the following: https://docs.gnosis-safe.io/infrastructure

What are you missing in terms of documentation?

**Comment by stebansaa** [comment]
The service architecture page helped a lot, and I have most things running on locally.  I'm stuck configuring Safe Config Service, it kinda works after some trial and error mostly from reviewing the code. A more detailed documentation could probably help on board more devs. I also tried discord channel to see if I could clear some simple questions, yet no dev related activity on it (unless I have the wrong channel).  Ultimately trying to learn and start helping with the code.

**Comment by stebansaa** [comment]
Thank you Frede, will keep testing.
