### ISSUE TITLE
Set the Url field to http://nginx:8000/cgw/v1/chains/1/hooks/events, results in "Enter a valid URL".

### ISSUE THREAD

**Issue by stebansaa** [safe-global/safe-infrastructure#32]
While following this guide: https://github.com/safe-global/safe-infrastructure/blob/main/docs/running_locally.md
And doing this:
"Set the Url field to http://nginx:8000/cgw/v1/chains/1/hooks/events"
It asks to "Enter a valid URL" 
it wont accept: http://nginx:8000/cgw/v1/chains/1/hooks/events
as a correct parameter.

**Comment by fmrsabino** [comment]
This issue was solved on version `v4.2.9` of the Safe Transaction Service: https://github.com/safe-global/safe-transaction-service/releases/tag/v4.2.9

Can you try setting `TXS_VERSION` to `v4.2.9`?

**Comment by stebansaa** [comment]
Updating to v4.2.9 did solve the issue, however now Im seeing this on Chrome when I try to connect metamask:

from the inspector tool console on Chrome:

wallet-connect-a5ae4fe8.js:25 Uncaught (in promise) Error: A "infuraKey" or a "rpc" object with a parameter of 1 must be included in the WalletConnect initialization object
    at Module.walletConnect [as default] (wallet-connect-a5ae4fe8.js:25:1)
    at onboard-e5e6136d.js:8440:1
    at async Promise.all (index 2)

The chainid is configured so it returns this: 

{"count":1,"next":null,"previous":null,"results":[{"chainId":"15555","chainName":"Test","shortName":"Testevm","description":"Testevm","l2":true,"rpcUri":{"authentication":"NO_AUTHENTICATION","value":"https://api.testevm.local"},"safeAppsRpcUri":{"authentication":"NO_AUTHENTICATION","value":"https://api.testevm.local"},"publicRpcUri":{"authentication":"NO_AUTHENTICATION","value":"https://api.testevm.local"},"blockExplorerUriTemplate":{"address":"https://rinkeby.etherscan.io/address/{{address}}","txHash":"https://rinkeby.etherscan.io/tx/{{txHash}}","api":"https://api-rinkeby.etherscan.io/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}"},"nativeCurrency":{"name":"Test","symbol":"Test","decimals":18,"logoUri":"/media/chains/15555/currency_logo.png"},"transactionService":"http://nginx:8000/txs","vpcTransactionService":"http://nginx:8000/txs","theme":{"textColor":"#ffffff","backgroundColor":"#000000"},"gasPrice":[],"ensRegistryAddress":null,"recommendedMasterCopyVersion":"1.3.0","disabledWallets":[],"features":[]}]}

**Comment by stebansaa** [comment]
This instruction also could be an issue:

"Set the Url field to http://nginx:8000/cgw/v1/chains/1/hooks/events"

is that 1, supposed to be the chainid? so for instance Im using 15555, so it should be:
Set the Url field to http://nginx:8000/cgw/v1/chains/1555/hooks/events

in any case there is no answer of any data from:  http://nginx:8000/cgw/v1/chains/1/hooks/events

**Comment by stebansaa** [comment]
solved the previous issue with the missing infura/rpc.... It is more a UX problem than anything. The user needs to first select an EVM from the options.  Yet they only become available after cache is fully cleared. Now dealing with a new issue. 

"safeContracts.ts:93 Uncaught (in promise) Error: GnosisSafeProxyFactory contract not found for chainId: 15555"

the contract does exist on chain 15555:
15555: GnosisSafeProxyFactory: 0xa6B71E26C5e0845f74c812102Ca7114b6a896AB2

will try to solve this one and update this thread.

**Comment by stebansaa** [comment]
after starting over on a new vm, again having problems with the chainid set on the API, not being found by the frontend.  I have carefully followed the documentation multiple times, the process is broken.
