### ISSUE TITLE
reqwest error TimedOut

### ISSUE THREAD

**Issue by benjamintshi** [safe-global/safe-infrastructure#48]
reqwest::Error { kind: Request, url: Url { scheme: \"http\", host: Some(Ipv4(52.74.121.192)), port: Some(8000), path: \"/txs/api/v1/safes/0x3DBa9E9EF6ac3B9F6394FA0E050cb9f60A295D1e/\", query: None, fragment: None }, source: TimedOut }"

**Comment by moisses89** [comment]
Please could you add more information about this? 
For example I can access to the admin, this safe exist in database, have no issues to access to config-service...

**Comment by benjamintshi** [comment]
@moisses89  hey bro , i can access to the admin and safe exist in databasee , v1/chains/  success
![image](https://user-images.githubusercontent.com/6221737/188168188-b5f984ad-5e53-40fb-ba36-47d3192cd06f.png)

**Comment by benjamintshi** [comment]
"code": 1337,
"message": "reqwest::Error { kind: Request, url: Url { scheme: \"http\", host: Some(Domain(\"localhost\")), port: Some(8000), path: \"/txs/api/v1/safes/0x9bDe47e92Cd1C2deb451d8332220AC1FFd01ff72/\", query: None, fragment: None }, source: hyper::Error(Connect, ConnectError(\"tcp connect error\", Os { code: 99, kind: AddrNotAvailable, message: \"Cannot assign requested address\" })) }"

**Comment by benjamintshi** [comment]
this local config  can not success run .

**Comment by benjamintshi** [comment]
cgw index.html 
Fetch error
Not Found ../openapi.json
