### ISSUE TITLE
Unable to load the new Safe

### ISSUE THREAD

**Issue by gzliudan** [safe-global/safe-infrastructure#60]
I deploy a local test enviroment according to guide: https://github.com/safe-global/safe-infrastructure/blob/main/docs/running_locally.md with commit 0802ae9dab50fe1ef48e815fda361c09710855e5. But below problem occurs when I open http://localhost:8080/ and create a new safe:

---

![1671175788362](https://user-images.githubusercontent.com/7695325/208046274-9ee84c5e-a574-4d23-a26e-49c4aa7390f8.png)

Click button `Get started`

![1671173237940](https://user-images.githubusercontent.com/7695325/208039189-5863a8b1-7692-49a0-9e4d-4abf816167ca.png)

After a few minutes

![1671173270269](https://user-images.githubusercontent.com/7695325/208039281-6f6c4764-d17e-4e57-8e57-d97ee3dcfbe7.png)

---

**File .env**

```text
REVERSE_PROXY_PORT=8000
REVERSE_PROXY_UI_PORT=8080

CFG_VERSION=latest
CGW_VERSION=latest
TXS_VERSION=latest

RPC_NODE_URL=https://rpc.ankr.com/eth_goerli

npm_package_version=1.0.0
```

---

**Chain config**

curl -s http://localhost:8000/cgw/v1/chains/5/ | jq

```json
{
  "transactionService": "http://nginx:8000/txs",
  "chainId": "5",
  "chainName": "Goerli",
  "shortName": "gor",
  "l2": true,
  "description": "Ethereum Testnet Görli",
  "rpcUri": {
    "authentication": "NO_AUTHENTICATION",
    "value": "https://rpc.ankr.com/eth_goerli"
  },
  "safeAppsRpcUri": {
    "authentication": "NO_AUTHENTICATION",
    "value": "https://rpc.ankr.com/eth_goerli"
  },
  "publicRpcUri": {
    "authentication": "NO_AUTHENTICATION",
    "value": "https://rpc.ankr.com/eth_goerli"
  },
  "blockExplorerUriTemplate": {
    "address": "https://goerli.etherscan.io/address/{{address}}",
    "txHash": "https://goerli.etherscan.io/tx/{{txHash}}",
    "api": "https://api-goerli.etherscan.io/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}"
  },
  "nativeCurrency": {
    "name": "Görli Ether",
    "symbol": "GOR",
    "decimals": 18,
    "logoUri": "/media/chains/5/currency_logo.png"
  },
  "theme": {
    "textColor": "#ffffff",
    "backgroundColor": "#4D99EB"
  },
  "ensRegistryAddress": "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e",
  "gasPrice": [
    {
      "type": "FIXED",
      "weiValue": "100000000000"
    },
    {
      "type": "FIXED",
      "weiValue": "24000000000"
    }
  ],
  "disabledWallets": [],
  "features": [
    "CONTRACT_INTERACTION",
    "DOMAIN_LOOKUP",
    "ERC1155",
    "ERC721",
    "SAFE_APPS",
    "SPENDING_LIMIT"
  ]
}
```

---

**Web Hook**

- Url: `http://nginx:8000/cgw/v1/chains/5/hooks/events`
- Authorization: `Basic some_random_token`

![1671174934759](https://user-images.githubusercontent.com/7695325/208043911-008ad0a3-ad65-41a1-8214-aa766c156210.png)

**Comment by gzliudan** [comment]
How much time and disk space are needed ? I use VM to test safe. Disk maybe is a hard limit.

**Comment by gzliudan** [comment]
Then how to make UI listen on ip 0.0.0.0 ? I have a VM with fast network, but it has no GUI, only can be accessed by remote network.

**Comment by Uxio0** [comment]
@gzliudan This repo is only an example of running the infra and putting things together, we cannot support with every configuration change 😉
