### ISSUE TITLE
How to verify safe on new network

### ISSUE THREAD

**Issue by gzliudan** [safe-global/safe-infrastructure#68]
I'm running safe-infrastructure in my VM with XDC network now. I can create safe on web browser successfully. How to verify that the safe works properly? 

BTW, does one safe-infrastructure support multiple chains at same time ?

**Comment by comverser** [comment]
I would like to pose the same question as well

**Comment by moisses89** [comment]
@gzliudan  you can test normal behaviours like:
- create safe and the safe is showed in the UI
- add,delete owners
- create transactions and sign
- interact with contracts
- receive and send tokens
> BTW, does one safe-infrastructure support multiple chains at same time ?

@gzliudan the unique service that don't support multichain is the transaction-service.
You can add more chains adding transaction service and workers for each chain and then add each chain information in the config-service.

**Comment by gzliudan** [comment]
My telegram username is same as GitHub.
