### ISSUE TITLE
Setup gnosis safe on my infrastructure has "Invalid CompatibilityFallbackHandler contract address" error

### ISSUE THREAD

**Issue by thespamer** [safe-global/safe-infrastructure#74]
I just followed all steps;

setup docker running_local and register a new chainID/RPC network, it works with my metamask, but:

1- When I try to "Create new safe" after choosing the name of safe, using my wallet as owner, set threshold, when Next button is clicked, the following javascript error shows:

`EthersAdapter.js:112 Uncaught (in promise) Error: Invalid CompatibilityFallbackHandler contract address
    at t.default.getCompatibilityFallbackHandlerContract (EthersAdapter.js:112:19)
    at k (safeContracts.ts:179:21)
    at index.tsx:58:29
    at s (runtime.js:45:40)
    at Generator._invoke (runtime.js:274:22)
    at P.forEach.e.<computed> [as next] (runtime.js:97:21)
    at r (_async_to_generator.mjs:3:20)
    at s (_async_to_generator.mjs:25:9)
    at _async_to_generator.mjs:32:7
    at new Promise (<anonymous>)`

What I need to do next/what is the issue?  
 **1- Using safe-contracts repo:**

`~/safe-contracts$ yarn deploy-all custom
yarn run v1.22.19
$ hardhat deploy-contracts --network custom
Nothing to compile
An unexpected error occurred:
Error: ERROR processing /home/ubuntu/safe-contracts/src/deploy/deploy_accessors.ts:
Error:
        **Safe factory not found for network 245022926. You can request a new deployment at https://github.com/safe-global/safe-singleton-factory.**
        For more information, see https://github.com/safe-global/safe-contracts#replay-protection-eip-155
`

**2- I just opened a issue requesting a new safe-factory:**
    https://github.com/safe-global/safe-singleton-factory/issues/107

    From safe-singleton-factory I just did `yarn deploy-all custom`, it generates a json file:
    
`{
	"gasPrice": 1000000000,
	"gasLimit": 16154360,
	"signerAddress": "0x5def6d46B26c1C672110FF9DdE09233E309c964f",
	"transaction": "0xf8a880843b9aca0083f67ef88080b853604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf3841d3581bfa049a9e05fd2ed60f0cc9a1b62d5dbdd651a297d715241067e246347046c9425a0a07e749bb77541e02c2858c324d5e0b83e0216927305481f7cfd67788ae09bdefe",
	"address": "0x7753Ee72051D187B208008cFa37669B7ED98Bf8c"
}`

and yarn submit
What is next to have this safe in my own infrastructure with my own RPC server?    
Were the steps shown here correct?

Regards,
Juliano

**Comment by thespamer** [comment]
The "Invalid CompatibilityFallbackHandler contract address " error is because I need this contract below deployed on my RPC? 

https://github.com/safe-global/safe-contracts/blob/main/contracts/handler/CompatibilityFallbackHandler.sol

**Comment by skimaharvey** [comment]
@thespamer I am having the same problem. Did you end up resolving it?

**Comment by thespamer** [comment]
@skimaharvey... yes, but our devs need to change all modules, there is no clear doc how to do it.

**Comment by Sj-001** [comment]
Hey @moisses89 , just a follow up, is the safe-deployments package updated?

**Comment by moisses89** [comment]
> Hey @moisses89 , just a follow up, is the safe-deployments package updated?

It is on 1.20.2 https://github.com/safe-global/web-core/blob/dev/package.json#L47 if you need other version you can request it in the [web-core](https://github.com/safe-global/web-core) project or add a PR.

**Comment by Sj-001** [comment]
https://github.com/safe-global/web-core/pull/1877 created @moisses89 . Its current in dev branch, not sure with one is used by infrastructure.
