### ISSUE TITLE
Running Goerli network for testing on the main branch does not work

### ISSUE THREAD

**Issue by comverser** [safe-global/safe-infrastructure#79]
The same question has been posted on <https://ethereum.stackexchange.com/questions/147811/run-the-safe-global-safe-infrastructure-service-for-a-sample-test>.

---
My goal is to run the [safe-infrastructure](https://github.com/safe-global/safe-infrastructure) service for a sample test by following the [Guide to run our services locally](https://github.com/safe-global/safe-infrastructure/blob/main/docs/running_locally.md).

I believe I followed the instructions correctly on the main branch (or commit [476c42d](https://github.com/safe-global/safe-infrastructure/commit/476c42d433db163bf5b409d1bf0e4a1d4e7c56ee)) with the [Georli chain](https://chainlist.org/chain/5), which is officially supported and should not have any compatibility or support issues. 

However, the service isn’t working.

# PROBLEM
##### Chrome DevTools Console
```
GET http://localhost:8000/cgw/v1/chains/5/safes/0x38b3aE5977220a8081De42a9045d8D2537e73871 404 (Not Found)
```
##### Chrome DevTools Headers
```
[General]
Request URL: http://localhost:8000/cgw/v1/chains/5/safes/0x38b3aE5977220a8081De42a9045d8D2537e73871
Request Method: GET
Status Code: 404 Not Found (from service worker)
Referrer Policy: strict-origin-when-cross-origin

[Response Headers]
access-control-allow-credentials: true
access-control-allow-headers: X-Requested-With, Content-Type, Authorization
access-control-allow-methods: POST, GET, OPTIONS
access-control-allow-origin: *
Connection: keep-alive
Content-Length: 26
Content-Type: application/json
Date: Wed, 22 Mar 2023 15:11:21 GMT
permissions-policy: interest-cohort=()
Server: nginx/1.23.3
x-content-type-options: nosniff
x-frame-options: SAMEORIGIN

[Request Headers]
Provisional headers are shown
Learn more
Referer: http://localhost:8080/
sec-ch-ua: "Brave";v="111", "Not(A:Brand";v="8", "Chromium";v="111"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "macOS"
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36
```
#### Chrome DevTools Response
```
{"code":42,"message":""}
```
##### Screenshot
![image](https://user-images.githubusercontent.com/24600425/226950134-4806d06f-b982-43e0-93a4-77a880eaac27.png)

# REPRODUCE
### Conditions
- Chain: Goerli
- RPC: https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161

### Step 1: setup your `.env`
```bash
REVERSE_PROXY_PORT=8000
REVERSE_PROXY_UI_PORT=8080

CFG_VERSION=latest
CGW_VERSION=latest
TXS_VERSION=latest
UI_VERSION=latest

RPC_NODE_URL=https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161
```

### Step 2: Setup Django superusers
```bash
# Option #1 - Automated way
cd scripts
sh run_locally.sh
```

### Step 3: Add your `ChainInfo`
Referred to the ChainInfo available in the official production information at https://safe-config.gnosis.io/api/v1/chains/
```bash
safe-infrastructure on  main
❯ curl -s http://localhost:8000/cfg/api/v1/chains/ | jq
{
  "count": 1,
  "next": null,
  "previous": null,
  "results": [
    {
      "chainId": "5",
      "chainName": "Goerli",
      "shortName": "gor",
      "description": "Ethereum Testnet Görli",
      "l2": true,
      "rpcUri": {
        "authentication": "NO_AUTHENTICATION",
        "value": "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
      },
      "safeAppsRpcUri": {
        "authentication": "NO_AUTHENTICATION",
        "value": "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
      },
      "publicRpcUri": {
        "authentication": "NO_AUTHENTICATION",
        "value": "https://goerli.infura.io/v3/9aa3d95b3bc440fa88ea12eaa4456161"
      },
      "blockExplorerUriTemplate": {
        "address": "https://goerli.etherscan.io/address/{{address}}",
        "txHash": "https://goerli.etherscan.io/tx/{{txHash}}",
        "api": "https://api-goerli.etherscan.io/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}"
      },
      "nativeCurrency": {
        "name": "Goerli Ether",
        "symbol": "GOR",
        "decimals": 18,
        "logoUri": "/media/chains/5/currency_logo.png"
      },
      "transactionService": "http://nginx:8000/txs",
      "vpcTransactionService": "http://nginx:8000/txs",
      "theme": {
        "textColor": "#ffffff",
        "backgroundColor": "#000000"
      },
      "gasPrice": [
        {
          "type": "fixed",
          "weiValue": "100000000000"
        }
      ],
      "ensRegistryAddress": "0x00000000000C2E074eC69A0dFb2997BA6C7d2e1e",
      "recommendedMasterCopyVersion": "1.3.0",
      "disabledWallets": [],
      "features": [
        "CONTRACT_INTERACTION",
        "DOMAIN_LOOKUP",
        "ERC1155",
        "ERC721",
        "SAFE_APPS",
        "SPENDING_LIMIT"
      ]
    }
  ]
}
```
### Step 4: Add your webhooks
- Url: `http://nginx:8000/cgw/v1/chains/5/hooks/events`
- Authorization: `Basic some_random_token`

## Safe Web App

**1. Connect to http://localhost:8080/welcome using a browser**

**2. Select the Goerli chain from the dropdown menu in the top right corner**

**3. Connect MetaMask wallet**

**4.1. Click the `+ Create New Safe` button**

**4.2. Select network and name your Safe -> Click the `Next` button**

![image](https://user-images.githubusercontent.com/24600425/226948584-5a6f3cea-5cd7-47f1-b402-ce067b99fc3b.png)

**4.3 Owners and confirmations ->  Click the `Next` button**
![image](https://user-images.githubusercontent.com/24600425/226949319-899b8607-68db-4315-a972-318424b4ea3f.png)

**4.4.1. Create new Safe -> Click the `Next` button**: the `Est. network fee` is not being updated and is still showing the initial value of 0.001 GOR
![image](https://user-images.githubusercontent.com/24600425/226949488-fa92b022-8579-4545-855d-b9e9a042881b.png)

**4.4.2. [Transaction](https://goerli.etherscan.io/tx/0xdf6f6bea07a71f9ea67dde331e76720cc342be838be8866a92719ba213031a0c)
![image](https://user-images.githubusercontent.com/24600425/226950047-207b1e90-8a8a-4b26-95c4-bb4168d9290b.png)**

**4.4.3. Error**
![image](https://user-images.githubusercontent.com/24600425/226950134-4806d06f-b982-43e0-93a4-77a880eaac27.png)

**Comment by moisses89** [comment]
I could see that your question was answered, could we close this issue? @comverser

**Comment by moisses89** [comment]
@comverser have you time to test it? :)

**Comment by moisses89** [comment]
No, ping me if you need something more.

**Comment by comverser** [comment]
@moisses89, I believe there may be some issues because the console messages from the Safe app (i.e. safe-infrastructure) in my test environment differ from those in your official environment. My question are: 
1.  How can I access the admin panel of the Safe Transaction Service running within Docker? 
2. The official Safe app takes less than three minutes to create a new Safe account. However, the app in my test environment did not complete the task even after an hour of testing and the periodic error messages (error code of 42) stopped early on. Do you know why this is happening?

**Comment by moisses89** [comment]
@comverser at this point more information is needed. 
If the cgw is showing 404 maybe is because the transaction-service indexer is not working. 
Could you check on transaction service if safe information endpoint return anything? http://localhost:8000/txs/api/v1/safes/0x38b3aE5977220a8081De42a9045d8D2537e73871/  
If yes, then the error is in the cgw, could you see in the docker logs for cgw container if there are any error? 
If not, then we should take a look to the worker-indexer container logs, could you check if the container show any error in the logs?

**Comment by moisses89** [comment]
`http://15.164.180.140:8080/txs/api/v1/safes/0x38b3aE5977220a8081De42a9045d8D2537e73871/`
I think that txs is in port 8000 right? 8080 is webpage. 
The second error is maybe because there are no messages but seems that your safe is indexed.

**Comment by comverser** [comment]
> `http://15.164.180.140:8080/txs/api/v1/safes/0x38b3aE5977220a8081De42a9045d8D2537e73871/`
> I think that txs is in port 8000 right? 8080 is webpage.
> The second error is maybe because there are no messages but seems that your safe is indexed.

I made the changes you suggested! Please refer to the initial post.

**Comment by moisses89** [comment]
@comverser the safe that you create was indexed and this was the goal of this issue. If you have other problem could you create another specific issue for that? We shouldn't mix issue s :)

**Comment by happyleow** [comment]
Hello @moisses89 Could you please take a look into my issue?
It's similar to the above issue, I am still waiting for the response from anyone on the team.
https://github.com/safe-global/safe-infrastructure/issues/141
Thank you.

**Comment by happyleow** [comment]
@moisses89 I read the answer you posted in StackExchange, but how do i access the admin panel of the Safe Transaction Service?
https://ethereum.stackexchange.com/questions/147811/run-the-safe-global-safe-infrastructure-service-for-a-sample-test
