### ISSUE TITLE
Mismatch in the ‘Block explorer URI API template’ when trying to add a custom chain

### ISSUE THREAD

**Issue by comverser** [safe-global/safe-infrastructure#81]
I’m trying to run this service locally and add a custom chain. In Step 3 of the process (Add your ChainInfo at http://localhost:8000/cfg/admin/chains/chain/add/), there’s an input field for the Block explorer URI API template. 

This field expects the chain’s explorer API to use query parameters like:
`https://api-apothem.blocksscan.io/api?module={{module}}&action={{action}}&address={{address}}&apiKey={{apiKey}}`. 

However, my custom chain uses path parameters instead, such as:
`https://explorerapi.wemix.com/api/ext/v1/accounts/{address_hash}/transactions`.

1) Is this field important?
2) What is the easiest way to resolve this issue?”

**Comment by hectorgomezv** [comment]
Hi @comverser,

That field is used to allow the Safe Web client to build links to block explorers, so no specific format is enforced (the field is just a string) at the infrastructure level. The Config Service also makes the Chain metadata accessible so an arbitrary service can consume this data through its API (Safe Web, Mobile, or any other service). To answer your questions:
1. This is used to build links to block explorers in the UI, so the importance is relative to how much you need that feature.
2. I'd say you'd need to adjust the code of the client consuming this data to match the format you put in the field.
