### ISSUE TITLE
Cannot import safe

### ISSUE THREAD

**Issue by skimaharvey** [safe-global/safe-infrastructure#87]
I have deployed all the contracts from the `v1.3.0` of the safe-contract repo (https://github.com/safe-global/safe-contracts/tree/v1.3.0-libs.0). I have used a non deterministic approach because we did not create a PR yet. 

The deployment was sucessful as you can see on the screenshot below: 

<img width="1172" alt="Screenshot 2023-04-26 at 17 49 31" src="https://user-images.githubusercontent.com/64636974/234614860-ee2044ca-88db-4691-8782-788e35454e59.png">

For some reason, every time I try to import a safe I get the following error:
<img width="789" alt="Screenshot 2023-04-26 at 17 54 30" src="https://user-images.githubusercontent.com/64636974/234615875-afe8241f-5cfe-4193-99dd-73cc1ece2e14.png">

Am I using the wrong safe-contract version? if so which one should I use?

Thanks! 

Checked in the console the 404 I am getting 
```
{"code":42,"message":"{\"message\":\"Params 'module' and 'action' are required parameters\",\"result\":null,\"status\":\"0\"}"}
```

**Comment by moisses89** [comment]
Hey @skimaharvey, did you follow the guide of this project? 
As you can see in the [readme](https://github.com/safe-global/safe-infrastructure) of this project the safe-infrastructure is composed by several services, in this case I would say to first take a look on transaction service. 
Transaction service has several workers and one of them could be considered the most important one that is the indexer. 
I'd say first take a look at that indexer and see if is indexing your blockchain, could you share the logs of the indexer? please no screenshots :)
Also I think that you can check in the admin of transaction service if your safe is indexed or use the api of transaction service with the endpoint /safes/{safe_address} to check if your safe is indexed.
I think that this is a good first step to debug your issue.

**Comment by skimaharvey** [comment]
@moisses89 thanks for your answer!
I see, the problem is that my blockchain is not yet being indexed. 
In this event, If I want to be able to run the safe infrastructure for testing. Do you think running the web-core with the gateway and the config services would be enough? 
I want to have the simplest infrastructure. What is your advice?
Thank you !
